#!/usr/bin/python3

# Python GPIO to DBUS simple client

import dbus
import time
import sys

def main():
    if len(sys.argv) < 2:
        print("Choose one of this port: ", [str(x) for x in
            dbus.SystemBus().get_object("com.devicehive.gpio.Info", 
                "/com/devicehive/gpio/Info").ls(
                dbus_interface='com.devicehive.gpio.Info')])
        return
    for i in range(1, len(sys.argv)):
        pin = dbus.SystemBus().get_object("com.devicehive.gpio.GpioPin",
            "/com/devicehive/gpio/{}".format(sys.argv[i]))
        pin.init("out", dbus_interface='com.devicehive.gpio.GpioPin')
        for _x in range(0, 5):
            pin.set(dbus_interface='com.devicehive.gpio.GpioPin')
            time.sleep(0.05)
            pin.clear(dbus_interface='com.devicehive.gpio.GpioPin')
            time.sleep(0.1)
            print("test")
        pin.deinit(dbus_interface='com.devicehive.gpio.GpioPin')


if __name__ == "__main__":
    main()
