#!/usr/bin/python3

# Python GPIO to DBUS simple client

import dbus
import time
import sys

def main():
    if len(sys.argv) < 2:
        print("Choose one of this port: ", [str(x) for x in
            dbus.SystemBus().get_object("com.devicehive.gpio.Info", 
            "/com/devicehive/gpio/Info").ls()])
        return
    for i in range(1, len(sys.argv)):
        pin = dbus.SystemBus().get_object("com.devicehive.gpio.GpioPin",
            "/com/devicehive/gpio/{}".format(sys.argv[i]))
        pin.init("out")
        for _x in range(0, 5):
            pin.set()
            time.sleep(0.05)
            pin.clear()
            time.sleep(0.1)
        pin.deinit()


if __name__ == "__main__":
    main()
